spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/myhospital
    username: root
    password: 156065
    driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
mybatis-plus:
    global-config:
      db-config:
        table-prefix: tb_
    configuration:
      map-underscore-to-camel-case: true