spring:
  redis:
    host: 192.168.142.133
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/myhospital
    username: root
    password: 156065
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: tb_